# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: MyTweets
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
      
        with:
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED
          filename: metrics.plugin.tweets.svg

          base: ""
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.MY_TWITTER_TOKEN }}
          plugin_tweets_user: ingenuity_brain
          plugin_tweets_limit: 3
  
  
