# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: MyWebSpeed
on:
  # Schedule updates (At 5:40 IST & 0:10 UTC)
  schedule: [{cron: "0 0 1 * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          filename: metrics.plugin.pagespeed.svg
          token: NOT_NEEDED
               

          # Options
          user: dalpatrathore
          template: classic
          base: ""
          config_timezone: Asia/Calcutta
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://dalpatrathore.vercel.app
          plugin_pagespeed_token: ${{ secrets.MY_WEB_TOKEN }}
