# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          filename: metrics.plugin.pagespeed.svg
          token: NOT_NEEDED

          # Options
          user: dalpatrathore
          template: classic
          base: ""
          config_timezone: Asia/Calcutta
          plugin_pagespeed: yes
          plugin_pagespeed_url: .user.website
